### PR TITLE
MC-14518 Refactor documentation to group sections

### PR DESCRIPTION
**Pull request by aaronalmeida**
#### Changes made

- Grouped relevant sections together under the sites section of stackpath 
- The sections should mirror the UI

Documentation sections: 
image

UI: 
image

### CODE REVIEW

**Review by ehudon — APPROVED** [review]
LGTM. One way could have reduce the noise in the diff is to use `git mv` to rename the files while retaining their history.

**Comment by aaronalmeida** [comment]
> LGTM. One way could have reduce the noise in the diff is to use `git mv` to renamed the files while retaining their history.

Never knew this! Will use it the next time I have a large diff

**Comment by ehudon** [comment]
@aaronalmeida I might be thiking out loud here, but have we validated that this refactoring does not break any link?

**Comment by m-orfanos** [comment]
@aaronalmeida how do the changes look? can you take a screen grab while going over the pages?

**Comment by aaronalmeida** [comment]
> @aaronalmeida how do the changes look? can you take a screen grab while going over the pages?

I think it looks great, everything looks super organized. Let me know if you want a screengrab of something more specific: 

https://user-images.githubusercontent.com/36786091/113919681-ddbba580-97b1-11eb-868e-6cb7a8beef44.mov

**Comment by aaronalmeida** [comment]
> @aaronalmeida I might be thiking out loud here, but have we validated that this refactoring does not break any link?

Doing a more thorough test right now, will update

Update: very nice catch. There were some places where the links weren't correct in the first place, some places with broken links before I made the change, and the few that I had to fix because of this change. 71e0b3784542a90c4cffb9ec13f1588cd35028a1

**Review by razine-bensari — APPROVED** [review]
lgtm

**Pull request merged**
